package app.yami.kmpnavigationdemo.util

val listItems = listOf(
    Item("Percy Jackson", "Perseus \"Percy\" Jackson is the Greek demigod son of Poseidon and Sally Jackson. He is the main protagonist and narrator of the Percy Jackson and the Olympians series and one of the main characters of The Heroes of Olympus series. He is the Head Counselor of Poseidon's Cabin at Camp Half-Blood and a former Praetor of the Twelfth Legion at Camp Jupiter, formerly belonging to the legion's Fifth Cohort. He was also the temporary host of the Egyptian goddess Nekhbet. He is currently the boyfriend of Annabeth Chase."),
    Item("Annabeth Chase", "Annabeth Chase is the Greek demigod daughter of Athena and Professor Frederick Chase, the half-sister of Bobby and Matthew Chase, and the paternal cousin of Norse demigod Magnus Chase. She is the deuteragonist in Percy Jackson and the Olympians series and is a main character in The Heroes of Olympus series, as she is one of the Seven demigods of the Prophecy of Seven. Annabeth is the architect of Olympus and the former head counselor of Athena's cabin. She is currently the girlfriend of Percy Jackson."),
    Item("Nico di Angelo", "Niccolò \"Nico\" di Angelo is the Italian-born Greek demigod son of Hades and the late Maria di Angelo, and the younger brother of the late Bianca di Angelo and the paternal half-brother of Roman demigod Hazel Levesque. He is a main character in the Percy Jackson and the Olympians, The Heroes of Olympus, and The Trials of Apollo series of books, and the protagonist and the title character of The Nico di Angelo Adventures series of books. He is known in the Underworld as the \"Ghost King\" after taking the title from Minos in The Battle of the Labyrinth. He is the boyfriend of Will Solace.", ),
    Item("Bianca di Angelo", "Bianca di Angelo was an Italian-born Greek demigod, a daughter of Hades and Maria di Angelo, and the older sister of Nico di Angelo. She became a Hunter of Artemis after being saved by them. She later died (killed by one of Hephaestus' defective automatons, Talos) at the age of twelve and chose to be reborn after reaching Elysium."),
    Item("Thalia Grace", "Thalia Grace is the Greek demigod daughter of Zeus and the mortal Beryl Grace, and the older sister of Roman demigod Jason Grace. After she was mortally wounded by attacking monsters, she was transformed into a pine tree on Half-Blood Hill, which still stands as the official border for Camp Half-Blood to this day. She was later resurrected by the Golden Fleece under the manipulations of Kronos in an attempt to control the Great Prophecy. She is currently the lieutenant of the Hunters of Artemis, leading them in the absence of the goddess after accepting Artemis' offer following a failed attempt by Kronos to use Thalia to destroy the gods."),
    Item("Luke", "Luke Castellan was the Greek demigod son of Hermes and May Castellan. He was one of the main antagonists of the Percy Jackson and the Olympians series. He was the Head Counselor at Hermes' Cabin. Although he allowed the Titan Lord Kronos to take possession of his body, Luke died as the hero of the Great Prophecy. Before dying, Luke stated an intention to go through rebirth rather than go to Elysium despite his hero's death, hoping to eventually reach the Isles of the Blest."),
)

data class Item(val title: String, val description: String)